# Generated by Django 4.2.7 on 2023-11-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_unidade'),
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Quantidade'),
        ),
    ]
