# Generated by Django 4.2.7 on 2023-11-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_alter_entradaproduto_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
