# Generated by Django 4.2.7 on 2023-12-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorio', models.CharField(choices=[('ARQ', 'Arquitetura'), ('IN', 'INPE'), ('AN', 'Pércio Reis'), ('WA', 'Wilson Aita'), ('S127', 'Sala 127'), ('S132', 'Sala 132'), ('S355', 'Sala 355')], default='', help_text='Auditório', max_length=50, verbose_name='Auditorio')),
                ('observacao', models.CharField(blank=True, help_text='Observação sobre o agendamento.', max_length=100, verbose_name='Observação')),
                ('status', models.CharField(choices=[('contato', 'Entrar em contato'), ('arrumar', 'Arrumar auditório'), ('pronto', 'Tudo pronto')], default='arrumar', help_text='Status do agendamento', max_length=50, verbose_name='Status')),
                ('event_name', models.CharField(blank=True, default='', help_text='Nome do evento.', max_length=255, verbose_name='Nome Evento')),
                ('number_of_people', models.IntegerField(blank=True, default=0, help_text='Número de pessoas.', verbose_name='Número de pessoas')),
                ('requester_name', models.CharField(blank=True, default='', help_text='Nome do solicitante.', max_length=255, verbose_name='Nome Solicitante')),
                ('requester_contact', models.CharField(blank=True, default='', help_text='Contato do solicitante.', max_length=155, verbose_name='Contato Solicitante')),
                ('equipment', models.TextField(blank=True, default='', help_text='Lista de equipamentos necessários.', verbose_name='Equipamentos')),
                ('data', models.DateField(blank=True, default='', help_text='Data do evento.', verbose_name='Data')),
                ('start_time', models.TimeField(blank=True, default='', help_text='Hora de início do evento.', verbose_name='Hora Início')),
                ('end_time', models.TimeField(blank=True, default='', help_text='Hora de fim do evento.', verbose_name='Hora Fim')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
