# Generated by Django 4.1.5 on 2023-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('contato', 'Entrar em contato'), ('arrumar', 'Arrumar auditório'), ('pronto', 'Tudo pronto')], default='contato', help_text='Status do agendamento', max_length=50, verbose_name='Status'),
        ),
    ]
