# Generated by Django 4.1.5 on 2023-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_auditorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do auditório.', max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Auditório',
                'verbose_name_plural': 'Auditórios',
            },
        ),
    ]
