# Generated by Django 4.1.5 on 2023-12-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agenda_auditorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='auditorio',
            field=models.ForeignKey(default='', help_text='Auditório', on_delete=django.db.models.deletion.CASCADE, to='agenda.auditorio', verbose_name='Auditório'),
        ),
    ]
