# Generated by Django 4.1.5 on 2023-12-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_agenda_auditorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='requester_contact',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='equipment',
            new_name='equipamento',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='event_name',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='end_time',
            new_name='hora_fim',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='start_time',
            new_name='hora_inicio',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='number_of_people',
            new_name='numero_pessoas',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='requester_name',
            new_name='solicitante',
        ),
    ]
