# Generated by Django 4.2.7 on 2023-11-25 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0004_alter_produto_quantidade_alter_produto_quantidademin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Saida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saida', to='produto.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saida de Produto',
                'verbose_name_plural': 'Saidas de Produtos',
                'ordering': ['-data_saida'],
            },
        ),
    ]
