# Generated by Django 4.2.7 on 2023-11-24 00:06

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Produto', max_length=50, verbose_name='Nome')),
                ('codigo', models.CharField(help_text='Código do Produto', max_length=10, verbose_name='Código')),
                ('observacao', models.CharField(help_text='Observações', max_length=200, verbose_name='Observações')),
                ('tipo', models.CharField(help_text='Tipo do Produto', max_length=50, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade em Estoque do produto', max_digits=5, max_length=5, verbose_name='Quantidade')),
                ('quantidademin', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, verbose_name='Quantidade minima')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='produtos', variations={'thumbnail': {'crop': True, 'height': 100, 'width': 100}}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
