# Generated by Django 4.2.7 on 2023-11-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(default='', help_text='Unidade', max_length=50, verbose_name='Unidade'),
        ),
    ]
