# Generated by Django 4.2.7 on 2023-11-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_quantidade_alter_produto_quantidademin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(help_text='Quantidade em Estoque do produto', verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidademin',
            field=models.IntegerField(verbose_name='Quantidade minima'),
        ),
    ]
