# Generated by Django 4.2.7 on 2023-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_quantidade_alter_produto_quantidademin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(help_text='Código do Produto', max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
